### ISSUE TITLE
Windows Evil-Helix

### ISSUE THREAD

**Issue by haininhhoang94** [etienne-k/helix#38]
Hello there, I would like to know if there is some compiled version of evil-helix on Windows, I have tried to compile it myself but I have failed. (It get link.exe error)

I would appreciate it if someone could help me with this. Thanks in advance!

**Comment by sdsalyer** [comment]
I was able to install [rustup-init.exe](https://win.rustup.rs/x86_64) and choose the defaults for installation options (`1.74.0-x86_64-pc-windows-msvc` via Visual Studio installer). Afterwards, cloning the repo and checkout @usagi-flow 's branch `feat-ci-ms` and `cd` into the directory. Then run `cargo install --path helix-term --locked`
 I got this command from the [build document](https://github.com/usagi-flow/evil-helix/blob/main/book/src/building-from-source.md), which may also be helpful.

In a fresh terminal, it's all there and working:
```
PS C:\Users\spenc> where.exe hx
C:\Users\spenc\.cargo\bin\hx.exe
PS C:\Users\spenc> hx --version
evil-helix release-20240716 (128999e9, helix 24.7)
```

Hope this helps in the meantime but it looks like usagi-flow just about has this implemented (I suspect the GNU toolchain is more problematic than the Visual Studio option on Windows, but this did take up an extra 5GB of disk space just to compile this rust app).

**Comment by usagi-flow** [comment]
Thank you for sharing your experiences!

As you correctly noted, I prepared a branch in which I tried to produce windows builds in a few different ways. 

Unfortunately, while helix actually builds, the tree-sitter grammars are causing issues (even with cargo-cross), and cargo-xwin simply freezes - for a reason still unknown to me.
And no bundled grammars means no syntax highlighting out-of-the-box. I'd rather get this right instead of releasing half-baked windows binaries.

Either way, thanks for your patience. I'll try to find some time in the coming days to think about how we can get this done.

**Comment by usagi-flow** [comment]
@haininhhoang94 @sdsalyer Thank you very much for your patience. It took a little while to find the time to find a solution (the treesitter integration made it hard to cross-compile), but we can now build windows binaries. 

I amended the last release and added a windows build to it, although I'd be happy to hear if it works for you. You can download it from here: https://github.com/usagi-flow/evil-helix/releases/tag/release-20240716
(_The artifact was produced by [this workflow run](https://github.com/usagi-flow/evil-helix/actions/runs/10633864909?pr=39), should you want to compare hashes._)

Regarding the installation: You should be able to extract the package anywhere, just make sure the extracted directory is on your `PATH`. If you use MSys2 / Cygwin / Git Bash..., you should be able to install it under `/opt` as recommended on in the README.

If someone could be so kind to confirm that it works well (especially syntax highlighting), I'll clean up and merge the PR.

**Comment by sdsalyer** [comment]
I think it's looking good. I didn't remove my old helix, but ran the hx.exe from the zip, e.g. `C:\Users\<username>\Downloads\helix-amd64-windows\helix\hx.exe`.  Hope this helps! Thanks for taking the time to add the Windows support!

![image](https://github.com/user-attachments/assets/f4dbf5a2-3211-4dd4-9bb1-126126c28907)

![image](https://github.com/user-attachments/assets/a26ef73d-8496-42e9-9afe-e14c5fcfa6da)

![image](https://github.com/user-attachments/assets/13bab9e8-5239-4626-ab2f-2211a7993fc9)

**Comment by koldle** [comment]
> @haininhhoang94 @sdsalyer Thank you very much for your patience. It took a little while to find the time to find a solution (the treesitter integration made it hard to cross-compile), but we can now build windows binaries.
> 
> I amended the last release and added a windows build to it, although I'd be happy to hear if it works for you. You can download it from here: https://github.com/usagi-flow/evil-helix/releases/tag/release-20240716 (_The artifact was produced by [this workflow run](https://github.com/usagi-flow/evil-helix/actions/runs/10633864909?pr=39), should you want to compare hashes._)
> 
> Regarding the installation: You should be able to extract the package anywhere, just make sure the extracted directory is on your `PATH`. If you use MSys2 / Cygwin / Git Bash..., you should be able to install it under `/opt` as recommended on in the README.
> 
> If someone could be so kind to confirm that it works well (especially syntax highlighting), I'll clean up and merge the PR.

Seems that the `editor.statusline.mode.normal/insert/select` setting doesnt work at current windows release?

**Comment by haininhhoang94** [comment]
my evil helix work as expected in windows. Thanks ! @usagi-flow and everyone!
