### ISSUE TITLE
Make it a fork on GitHub

### ISSUE THREAD

**Issue by antoyo** [etienne-k/helix#9]
Hi.
Any reason why this doesn't show as a fork of helix on GitHub?
I would find this useful to compare with the original helix.
Thanks.

**Comment by usagi-flow** [comment]
Unfortunately, there is a very specific reason indeed. Moreover, this repository used to be an actual GitHub fork until last week, where I submitted a support ticket to have this repository "detached".

In a forked repository, when you create a PR, GitHub by default selects the default branch of the _upstream_ repository as the base branch, and thinks you want to create a PR in the upstream repository. This is very annoying and error-prone when you want to merge changes which aren't meant to be submitted to upstream (e.g. Vim keybindings).

There is no known setting to configure this, there's a lot of people wanting such a setting, and it doesn't seem like GitHub cares much about it: https://github.com/orgs/community/discussions/11729

I wish we could combine the best of two worlds, but that decision lies in GitHub's hands, unfortunately.
I'm open to any suggestions, that said.

**Comment by antoyo** [comment]
I completely understand since I have the same problems on one of my projects.
Let's hope it's going to be fixed eventually.
